---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  storageClassName: "storageclassfancyname"
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/volumes/vol1"
---
